### ISSUE TITLE
Incorrect naming

### ISSUE THREAD

**Issue by MarkiyanFostyak** [danahrechyn123/Task3#1]
https://github.com/danahrechyn123/Task3/blob/c98cc1d89a766b4baeb48969633633aaf0998f52/Task3_5_Dana_Anzela/Complex.cs#L29
The first letter of the public method name should be in upper case.

**Comment by danahrechyn123** [comment]
Done!
![image](https://user-images.githubusercontent.com/28107512/38869850-b90b92be-4254-11e8-93f2-2dce8e3d28c6.png)
