### ISSUE TITLE
Labels using

### ISSUE THREAD

**Issue by MarkiyanFostyak** [danahrechyn123/Task3#2]
https://github.com/danahrechyn123/Task3/blob/c98cc1d89a766b4baeb48969633633aaf0998f52/Task3_5_Dana_Anzela/Complex.cs#L31
Using labels leads to writing spaghetti code. Please have a look [here](https://en.wikipedia.org/wiki/Spaghetti_code).

**Comment by danahrechyn123** [comment]
done!
