### ISSUE TITLE
Duplication of fields 

### ISSUE THREAD

**Issue by MarkiyanFostyak** [danahrechyn123/Task3#5]
https://github.com/danahrechyn123/Task3/blob/c98cc1d89a766b4baeb48969633633aaf0998f52/Task3_5_Dana_Anzela/Complex.cs#L121-L125
These fields along with getters should be changed to: 
```
public Re { get; set; }
public Im { get; set; }
```
If you don't have any specific set or get logic, you don't need an explicit private field.

**Comment by danahrechyn123** [comment]
[done!``]

**Comment by danahrechyn123** [comment]
done!
