### ISSUE TITLE
UI specific logic inside class

### ISSUE THREAD

**Issue by MarkiyanFostyak** [danahrechyn123/Task3#8]
https://github.com/danahrechyn123/Task3/blob/c98cc1d89a766b4baeb48969633633aaf0998f52/Task3_5_Dana_Anzela/Complex.cs#L29
This logic should not be implemented in the class. UI should be separated from business logic.

**Comment by danahrechyn123** [comment]
done!
Input/Output are in Tasks now.
![image](https://user-images.githubusercontent.com/28107512/38870091-6824a16e-4255-11e8-8fd1-caf32042cfab.png)
